In [ ]:
#lab 10 decision tree for weather


#lab 10 decision tree for weather

# Step 1 : loading data

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
from google.colab import drive
# mount google drive
drive.mount('/content/drive')

# path to your csv in drive
weather_file= '/content/drive/MyDrive/CI345_ML/Data/Weather.csv'

weather_table = pd.read_csv(weather_file)
weather_table

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

    Day   Outlook  Temp Humidity    Wind PlayTennis
0    D1     Sunny   Hot     High    Weak         No
1    D2     Sunny   Hot     High  Strong         No
2    D3  Overcast   Hot     High    Weak        Yes
3    D4      Rain  Mild     High    Weak        Yes
4    D5      Rain  Cool   Normal    Weak        Yes
5    D6      Rain  Cool   Normal  Strong         No
6    D7  Overcast  Cool   Normal    Weak        Yes
7    D8     Sunny  Mild     High    Weak         No
8    D9     Sunny  Cold   Normal    Weak        Yes
9   D10      Rain  Mild   Normal  Strong        Yes
10  D11     Sunny  Mild   Normal  Strong        Yes
11  D12  Overcast  Mild     High  Strong        Yes
12  D13  Overcast   Hot   Normal    Weak        Yes
13  D14      Rain  Mild     High  Strong         No

# step 2: Basic data analyze

In [ ]:
df = weather_table.copy()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Day         14 non-null     object
 1   Outlook     14 non-null     object
 2   Temp        14 non-null     object
 3   Humidity    14 non-null     object
 4   Wind        14 non-null     object
 5   PlayTennis  14 non-null     object
dtypes: object(6)
memory usage: 804.0+ bytes

In [ ]:
df.columns

Index(['Day', 'Outlook', 'Temp', 'Humidity', 'Wind', 'PlayTennis'], dtype='object')

In [ ]:
df.shape

(14, 6)

In [ ]:
df.isnull().sum()

Day           0
Outlook       0
Temp          0
Humidity      0
Wind          0
PlayTennis    0
dtype: int64

# step 3: Data visualizatipon

In [ ]:
res = df.PlayTennis.value_counts()
res.Plot(kind = 'pie', autopct = '1%    ')

# Step 4: Processsing data

In [ ]:

#  method 1:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Humidity'] = le.fit_transform(df['Humidity'])
df['Wind'] = le.fit_transform(df['Wind'])
df.heaad(14)

In [ ]:
# method 2: use mappingf method
Outloop_mapping = {'Sunny':0, 'Overcast':1, 'Rain':2}
Temp_mapping = {'Hot':0, 'Mild':1, 'Cool':2, 'Cold':3}

df['Outlook'] =df['Out;ook'].map({'Sunny':0, 'Overcast':1, 'Rain':2})
df['Temp'] = df['Temp'].map({'Hot':0, 'Mild':1, 'Cold':2, 'Cold':3})
df.head(5)

NameError: name 'df' is not defined

# step 5: get data and target

In [ ]:
data = df['Outlook','Temp','Humidity','Wind']
target = df['PlayTennis']
target.head(2)
data.head(2)

# step 6: classification by dt

In [ ]:
from sklearn.model_selection import train_test_split

data_train, data_test, target_train, target_test = \
train_test_split(data, target, random_state = 13, test_size = 0.4)

print(data_train.shape)
print(data_test.shape)

print(target_train.shape)
print(target_test.shape)

NameError: name 'data' is not defined

In [ ]:
from sklearn import tree
dt.classisier = tree.DecisionTreeClassifier(max_depth = 3)
dt=