<a href="https://colab.research.google.com/github/pa24117-crypto/CI345-ml/blob/main/ML_Final_Project_Disicpline_vs_Distraction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#ML - Final Project
###Disicpline vs Distraction Dataset
#Research Question: Can we predict procrastination levels from a student's behavioral profile including academic outcomes?

# Step 1 -- Loading Data

In [ ]:
import pandas as pd
import numpy as np

from google.colab import drive

#Mount Google Drive
drive.mount('/content/drive')

# Path to your CSV in Drive
distraction_file = '/content/drive/MyDrive/CI345_ML/Data/procrastination_dataset.csv'

df = pd.read_csv(distraction_file)

print(df.head(3))
print(df.columns)
print("Dataset Shape: ", df.shape)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
   user_id  study_hours  sleep_hours  screen_time_total  social_media_time  \
0        1          5.9          5.9                9.0                3.9
1        2          3.1          4.8                9.3                6.1
2        3          1.5          5.5                9.7                4.3

   task_delay_minutes  focus_score  stress_level  motivation_level  \
0                 142            1             9                 4
1                  81            2             5                 4
2                  89            3             4                 4

   study_session_length  ...  caffeine_intake  multitasking_level  \
0                    61  ...                5              Medium
1                    59  ...                0              Medium
2                    61  ...                2                 Low

   study_environment  peak_productivity_time  deadline_type task_difficulty  \
0           Moderate               Afternoon       Flexible            Hard
1              Noisy                   Night       Flexible            Hard
2           Moderate                   Night       Flexible          Medium

  deadline_urgency productivity_score task_completion_rate  \
0              Low                1.0                   85
1              Low                1.0                   95
2           Medium                1.0                   82

  procrastination_level
0                  High
1                Medium
2                Medium

[3 rows x 24 columns]
Index(['user_id', 'study_hours', 'sleep_hours', 'screen_time_total',
       'social_media_time', 'task_delay_minutes', 'focus_score',
       'stress_level', 'motivation_level', 'study_session_length',
       'break_frequency', 'notifications_per_day', 'phone_pickups_per_day',
       'exercise_minutes', 'caffeine_intake', 'multitasking_level',
       'study_environment', 'peak_productivity_time', 'deadline_type',
       'task_difficulty', 'deadline_urgency', 'productivity_score',
       'task_completion_rate', 'procrastination_level'],
      dtype='object')
Dataset Shape:  (2000, 24)

#Step 2 -- Data Analysis

In [ ]:
#Creating copy of original data set
df.copy()

#Dropping Column User ID - No correlation to the dataset
df.drop(columns=['user_id'], inplace=True)
# Show Basic Info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 23 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   study_hours             2000 non-null   float64
 1   sleep_hours             2000 non-null   float64
 2   screen_time_total       2000 non-null   float64
 3   social_media_time       2000 non-null   float64
 4   task_delay_minutes      2000 non-null   int64
 5   focus_score             2000 non-null   int64
 6   stress_level            2000 non-null   int64
 7   motivation_level        2000 non-null   int64
 8   study_session_length    2000 non-null   int64
 9   break_frequency         2000 non-null   int64
 10  notifications_per_day   2000 non-null   int64
 11  phone_pickups_per_day   2000 non-null   int64
 12  exercise_minutes        2000 non-null   int64
 13  caffeine_intake         2000 non-null   int64
 14  multitasking_level      2000 non-null   object
 15  study_environment       2000 non-null   object
 16  peak_productivity_time  2000 non-null   object
 17  deadline_type           2000 non-null   object
 18  task_difficulty         2000 non-null   object
 19  deadline_urgency        2000 non-null   object
 20  productivity_score      2000 non-null   float64
 21  task_completion_rate    2000 non-null   int64
 22  procrastination_level   2000 non-null   object
dtypes: float64(5), int64(11), object(7)
memory usage: 359.5+ KB

In [ ]:

#Show number rows and columns
df.shape

(2000, 23)

In [ ]:
#Show column names
df.columns

Index(['study_hours', 'sleep_hours', 'screen_time_total', 'social_media_time',
       'task_delay_minutes', 'focus_score', 'stress_level', 'motivation_level',
       'study_session_length', 'break_frequency', 'notifications_per_day',
       'phone_pickups_per_day', 'exercise_minutes', 'caffeine_intake',
       'multitasking_level', 'study_environment', 'peak_productivity_time',
       'deadline_type', 'task_difficulty', 'deadline_urgency',
       'productivity_score', 'task_completion_rate', 'procrastination_level'],
      dtype='object')

In [ ]:
#Show data types
df.dtypes

study_hours               float64
sleep_hours               float64
screen_time_total         float64
social_media_time         float64
task_delay_minutes          int64
focus_score                 int64
stress_level                int64
motivation_level            int64
study_session_length        int64
break_frequency             int64
notifications_per_day       int64
phone_pickups_per_day       int64
exercise_minutes            int64
caffeine_intake             int64
multitasking_level         object
study_environment          object
peak_productivity_time     object
deadline_type              object
task_difficulty            object
deadline_urgency           object
productivity_score        float64
task_completion_rate        int64
procrastination_level      object
dtype: object

In [ ]:
#Show missing data
df.isnull().sum()

study_hours               0
sleep_hours               0
screen_time_total         0
social_media_time         0
task_delay_minutes        0
focus_score               0
stress_level              0
motivation_level          0
study_session_length      0
break_frequency           0
notifications_per_day     0
phone_pickups_per_day     0
exercise_minutes          0
caffeine_intake           0
multitasking_level        0
study_environment         0
peak_productivity_time    0
deadline_type             0
task_difficulty           0
deadline_urgency          0
productivity_score        0
task_completion_rate      0
procrastination_level     0
dtype: int64

In [ ]:
#Show descriptive statistics
df.describe()

,study_hours,sleep_hours,screen_time_total,social_media_time,task_delay_minutes,focus_score,stress_level,motivation_level,study_session_length,break_frequency,notifications_per_day,phone_pickups_per_day,exercise_minutes,caffeine_intake,productivity_score,task_completion_rate
count,2000.00000,2000.000000,2000.000000,2000.000000,2000.000000,2000.00000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000
mean,5.45240,5.445250,7.920450,5.179850,70.966500,3.40250,5.221000,4.984500,74.481500,4.341500,119.194500,53.020500,20.088000,2.033500,2.814900,94.558000
std,2.70287,1.077306,1.766272,1.642601,46.777136,2.37725,2.256037,2.269104,20.856274,2.149928,31.882251,11.289057,14.256889,1.405121,2.291585,11.184059
min,0.00000,4.000000,2.100000,1.000000,0.000000,-2.00000,1.000000,1.000000,10.000000,0.000000,10.000000,14.000000,0.000000,0.000000,1.000000,31.000000
25%,3.40000,4.500000,6.800000,4.000000,34.000000,1.00000,3.000000,3.000000,60.000000,3.000000,98.750000,46.000000,9.000000,1.000000,1.000000,95.000000
50%,5.50000,5.400000,8.200000,5.100000,68.000000,3.00000,5.000000,5.000000,75.000000,4.000000,119.000000,53.000000,19.000000,2.000000,1.600000,100.000000
75%,7.60000,6.200000,9.500000,6.400000,105.000000,5.00000,7.000000,7.000000,89.000000,6.000000,141.000000,61.000000,30.000000,3.000000,4.300000,100.000000
max,10.00000,9.000000,10.000000,9.000000,180.000000,10.00000,11.000000,10.000000,120.000000,11.000000,200.000000,80.000000,60.000000,5.000000,10.000000,100.000000

In [ ]:
#Target Distrubution
print(df['procrastination_lvl'].value_counts())

print("\nClass proportions:")
print(df['procrastination_lvl'].value_counts(normalize=True))

KeyError: 'procrastination_lvl'

In [ ]:
#Shows the categories and their values
cat_cols = df.select_dtypes(include='object').columns
for col in cat_cols:
    print(f"{col}: {df[col].unique().tolist()}")

#Step 3 -- Data Visualization

In [ ]:
import seaborn as sns

plt.figure(figsize=(5, 3))
ax = sns.countplot(data=df, x='procrastination_lvl',
                   order=['Low', 'Medium', 'High'],
                   palette={'Low':'green', 'Medium':'yellow', 'High':'red'})

# Add counts and percentages
for bar in ax.patches:
    count = bar.get_height()
    pct = count / len(df) * 100
    ax.text(bar.get_x() + bar.get_width() / 2,
            count + 10,
            f'{int(count)}\n({pct:.1f}%)',
            ha='center', va='bottom', fontsize=10)

plt.title('Procrastination levels')
plt.xlabel('Procrastination level')
plt.ylabel('Number of students')
plt.ylim(0, df['procrastination_lvl'].value_counts().max() * 1.2)
plt.show()

In [ ]:
plt.figure(figsize=(5, 3))
ax = sns.barplot(data=df, x='procrastination_lvl', y='completion_rate',
                 order=['Low', 'Medium', 'High'],
                 palette={'Low':'green', 'Medium':'orange', 'High':'red'})

for container in ax.containers:
    ax.bar_label(container, fmt='%.1f%%', padding=3)

plt.title('Completion rate by procrastination level')
plt.xlabel('Procrastination level')
plt.ylabel('Mean completion rate (%)')
plt.ylim(0, 115)
plt.show()

In [ ]:
behavioral_features = [
    'study_hrs', 'sleep_hrs', 'screen_time_by_day', 'social_media_time',
    'task_delay_min', 'focus_score', 'study_session_length', 'completion_rate',
    'exercise_min', 'caffeine_intake', 'break_frequency',
    'stress_lvl', 'motivation_lvl'
]

colors = {'Low': 'green', 'Medium': 'orange', 'High': 'red'}

fig, axes = plt.subplots(3, 5, figsize=(22, 12))
axes = axes.flatten()

for i, (feat, ax) in enumerate(zip(behavioral_features, axes)):
    for lvl, color in colors.items():
        sns.histplot(data=df[df['procrastination_lvl'] == lvl],
                     x=feat, bins=25, alpha=0.5, color=color,
                     label=lvl, ax=ax, edgecolor='none')
    ax.set_title(feat.replace('_', ' ').title(), fontsize=11)
    ax.set_xlabel('')
    ax.set_ylabel('Count', fontsize=9)
    ax.legend(fontsize=8, frameon=False)
    ax.spines[['top', 'right']].set_visible(False)

[ax.set_visible(False) for ax in axes[len(behavioral_features):]]

plt.suptitle('Behavioral feature distributions by procrastination level', y=1.01)
plt.tight_layout()
plt.show()

# Step 4 -- Data Processing

In [ ]:
from sklearn.preprocessing import OrdinalEncoder, LabelEncoder

#Ordinal encode — preserve Low < Medium < High order
ord_enc = OrdinalEncoder(categories=[
    ['Low', 'Medium', 'High'],   # multitasking_lvl
    ['Easy', 'Medium', 'Hard'],  # difficulty_lvl
    ['Low', 'Medium', 'High'],   # deadline_urgency
])

ord_cols = ['multitasking_lvl', 'difficulty_lvl', 'deadline_urgency']
df[ord_cols] = ord_enc.fit_transform(df[ord_cols])

#One-hot encode
df = pd.get_dummies(df, columns=['study_environment', 'peak_productivity'],dtype=int)

#Binary encode
df['deadline'] = (df['deadline'] == 'Strict').astype(int)

#Encoding target
le = LabelEncoder()
df['procrastination_lvl_enc'] = le.fit_transform(df['procrastination_lvl'])

#Verify
print(df.shape)
print(df.dtypes.value_counts())

#Step 5 -- Seperating Data and target

In [ ]:
print(df.columns)

#Seperating Features

col = ['study_hrs', 'sleep_hrs', 'screen_time_by_day', 'social_media_time',
       'task_delay_min', 'focus_score', 'stress_lvl', 'motivation_lvl',
       'study_session_length', 'break_frequency', 'notifications_per_day',
       'phone_use_per_day', 'exercise_min', 'caffeine_intake',
       'multitasking_lvl', 'deadline', 'difficulty_lvl', 'deadline_urgency',
       'productivity_score', 'completion_rate',
       'study_environment_Moderate', 'study_environment_Noisy',
       'study_environment_Quiet', 'peak_productivity_Afternoon',
       'peak_productivity_Morning', 'peak_productivity_Night']

# Data
X = df[col]

# Target
y = df['procrastination_lvl_enc']

print(X.shape)
print(y.shape)
print("---------------")
print(y.head(2))
print(X.head(3))

#Step 6 -- Training Classifiers

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test  = train_test_split (X, y, random_state = 42, test_size = 0.2)

    #Review the data and target
print('-- Split Data -- ')
print(X_train.shape)
print(X_test.shape)
print()
print('-- Split Target --')
print(y_train.shape)
print(y_test.shape)

In [ ]:
        # Show training and testing data
print('\t-- Checking Split Data -- ')
print()
print(X_train[:3])
print(X_test[:3])
print()
print('\t-- Checking Target Data -- ')
print()
print(y_train[:3])
print(y_test[:3])

#Classifier 1 -- Standard Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

# Step 1: Create Logistic Regression Classifier
lr_classifier = LogisticRegression(max_iter=1000, random_state=42)

# Step 2: Training (Use X_train instead of data_train)
lr_classifier.fit(X_train, y_train)
print(lr_classifier)

# Step 3: Testing (Use X_test instead of data_test)
y_pred = lr_classifier.predict(X_test)

# Step 4: Evaluation, Classification Report
print("\n--- Classification Report ---")
print(classification_report(y_test, y_pred))

# Step 5: Evaluation, Confusion Matrix
matrix = confusion_matrix(y_true=y_test, y_pred= y_pred)
print('--- Confusion Matrix ---')
print(matrix)

#Classifier 2 -- Decision Tree

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix

# Step 1: Create Decision Tree
dt_classifier = DecisionTreeClassifier(max_depth=5,random_state=42)

# Step 2: Training (Use X_train instead of data_train)
dt_classifier.fit(X=X_train, y=y_train)
print(dt_classifier)

# Step 3: Testing (Use X_test instead of data_test)
predicted = dt_classifier.predict(X=X_test)

# Step 4: Evaluation, Classification Report
print("\n--- Classification Report ---")
print(classification_report(y_test, predicted))

# Step 5: Evaluation, Confusion Matrix
matrix = confusion_matrix(y_true=y_test, y_pred=predicted)
print('--- Confusion Matrix ---')
print(matrix)

#Classfier 3 -- Random Forest Classifier

In [ ]:
import pandas as pd
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.ensemble import RandomForestClassifier

# Step 1: Create Random Forest Classifier
rf_classifier = RandomForestClassifier(n_estimators=500, random_state=42)

# Step 2: Training
rf_classifier.fit(X_train, y_train)
print(rf_classifier)

# Step 3: Testing (Use X_test instead of data_test)
y_pred = rf_classifier.predict(X_test)

# Step 4: Evaluation, Classification Report
print("\n--- Classification Report ---")
print(classification_report(y_test, y_pred))

# Step 5: Evaluation, Confusion Matrix
matrix = confusion_matrix(y_true=y_test, y_pred = y_pred)
print('--- Confusion Matrix ---')
print(matrix)